### ISSUE TITLE
I have a problem when running the program

### ISSUE THREAD

**Issue by FranShavee** [y31ling/algorithm-to-predict-Shanghai-major#1]
line 144
    print(f"{teams[team]["name"]}: \n3-0: {prob30:.2f}%, 3-1/2: {prob31or32:.2f}%, 0-3: {prob03:.2f}%, 1/2-3: {prob13or23:.2f}%")
                          ^^^^
SyntaxError: f-string: unmatched '['

python version 3.11

**Comment by y31ling** [comment]
I have never met this error, Maybe you can try changing the quotes?
i.e.:change <teams[team]["name"]> into <teams[team]['name']>

the new code should be:
print(f"{teams[team]['name']}: \n3-0: {prob30:.2f}%, 3-1/2: {prob31or32:.2f}%, 0-3: {prob03:.2f}%, 1/2-3: {prob13or23:.2f}%")

**Comment by FranShavee** [comment]
Thanks, the issue has been solved
